<?php # $Id: lang_de.inc.php,v 1.3 2005/05/17 11:43:07 garvinhicking Exp $
@define('THEME_COLORSET', 'Farbwahl');
@define('THEME_COLORSET_DESC', 'Farbset auswählen, welches das Blog benutzen soll');
@define('MY_COLORSET', 'Mein Farbset');
@define('FOOTER_POSITION', 'Position der Fusszeile des Eintrags');
@define('FOOTER_POSITION_DESC', 'Komplett unter dem Eintrag oder aufgeteilt in eine Zeile über und mehrere Zeilen unter dem Eintrag');
@define('SPLIT_ENTRY', 'Geteilt');
@define('BELOW_ENTRY', 'Unten');
@define('COCOMMENT_ACTIVE', 'coComment integrieren');
@define('COCOMMENT_ACTIVE_DESC', 'coComment in Kommentarformulare einbinden');
@define('USE_COCOMMENT','coComment einbinden');
@define('NO_COCOMMENT', 'coComment nicht einbinden');
@define('COUNTER_CODE', 'Counter-Code');
@define('COUNTER_CODE_DESC', 'Hier Code für Counter und/oder Statistik-Tools einfügen');
@define('USE_COUNTER', 'Counter einbinden');
@define('USE_COUNTER_DESC', 'Oben eingegeben Counter-Code in das Blog einbinden');
@define('CC_POS', 'Ja');
@define('CC_NEG', 'Nein');
@define('FOOTER_TEXT', 'Footer-Text');
@define('FOOTER_TEXT_DESC', 'Hier zusätzlichen Text, der im Seitenfuss erscheinen soll, einfügen.');
@define('USE_FOOTER_TEXT', 'Text einbinden');
@define('USE_FOOTER_TEXT_DESC', 'Oben eingegeben Text in den Seitenfuss einbinden');
@define('FT_POS', 'Ja');
@define('FT_NEG', 'Nein');
@define('NAVLINK_AMOUNT', 'Anzahl der navbar-Links');
@define('NAVLINK_AMOUNT_DESC', 'Anzahl der Links in der Navigationsleiste (Styles verwalten-Seite muss danach neu geladen werden)');
@define('NAV_LINK_TEXT', 'Navigationsleisten-Link');
@define('NAV_LINK_DESC', 'Text für den Navigationsleisten-Link');
@define('NAV_LINK_URL', 'URL des Navigationsleisten-Links');
@define('NAV_LINK_URL_DESC', 'Voller URL des Navigationsleisten-Links');
@define('NAV_DEFAULT_0', 'Über');
@define('NAV_DEFAULT_1', 'Fotos');
@define('NAV_DEFAULT_2', 'Impressum');
@define('NAV_DEFAULT_3', 'Musik');
@define('NAV_DEFAULT_4', 'Kontakt');
?>